# Generated by Django 2.1.2 on 2018-10-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('price', models.IntegerField(verbose_name='price')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('sold_quantity', models.IntegerField(default=0, verbose_name='Sold Quantity')),
            ],
        ),
    ]
