# Generated by Django 2.1.2 on 2018-10-19 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20181019_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
    ]
